{"uuid": "b296e289-4546-4bef-bcd8-9ad4faacf156", "children": ["f450586c-c212-4f47-b90e-d1cb94174ee6"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: Could not reach host. Are you offline?\n", "trace": "  File \"C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Acer\\Desktop\\piton\\Python\\lesson_10\\tests\\test_shop.py\", line 18, in browser\n    service = FirefoxService(GeckoDriverManager().install())\n                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\firefox.py\", line 39, in install\n    driver_path = self._get_driver_binary_path(self.driver)\n  File \"C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\core\\manager.py\", line 40, in _get_driver_binary_path\n    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))\n                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\drivers\\firefox.py\", line 37, in get_driver_download_url\n    driver_version_to_download = self.get_driver_version_to_download()\n  File \"C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\core\\driver.py\", line 48, in get_driver_version_to_download\n    return self.get_latest_release_version()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\drivers\\firefox.py\", line 29, in get_latest_release_version\n    resp = self._http_client.get(\n        url=self.latest_release_url,\n        headers=self.auth_header\n    )\n  File \"C:\\Users\\Acer\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\core\\http.py\", line 35, in get\n    raise exceptions.ConnectionError(f\"Could not reach host. Are you offline?\")\n"}, "start": 1755695698273, "stop": 1755695699510}], "start": 1755695698273, "stop": 1755695699638}